# Generated by Django 3.0.5 on 2020-05-11 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('ProgramIcon', models.ImageField(upload_to='img')),
                ('ProgramBrief', models.CharField(max_length=256, verbose_name='项目简介')),
                ('ProgramName', models.CharField(max_length=64, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'df_Program',
            },
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('SubProgramName', models.CharField(max_length=64, verbose_name='子项目名称')),
                ('SubProgramBrief', models.CharField(max_length=256, verbose_name='子项目简介')),
                ('SubProgramId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Program.BigProgram', verbose_name='子项目编号')),
            ],
            options={
                'verbose_name': '子项目',
                'verbose_name_plural': '子项目',
                'db_table': 'df_SubProgram',
            },
        ),
    ]
