# Generated by Django 3.0.5 on 2020-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprogram',
            name='SubProgramDoc',
            field=models.FileField(null=True, upload_to='doc'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='SubProgramHtml',
            field=models.FileField(null=True, upload_to='Html'),
        ),
    ]
