# Generated by Django 3.0.5 on 2020-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0002_auto_20200512_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='SubProgramHtml',
            field=models.FileField(blank=True, null=True, upload_to='Html'),
        ),
    ]
