# Generated by Django 2.1.8 on 2020-05-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('LiftName', models.CharField(max_length=128, verbose_name='图片名称')),
                ('LiftIcon', models.ImageField(upload_to='img')),
            ],
            options={
                'verbose_name': '生活',
                'verbose_name_plural': '生活',
                'db_table': 'df_Life',
            },
        ),
        migrations.CreateModel(
            name='LiftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LiftType', models.CharField(max_length=128, verbose_name='图片类型')),
            ],
            options={
                'verbose_name': '生活类型',
                'verbose_name_plural': '生活类型',
                'db_table': 'df_LifeType',
            },
        ),
        migrations.AddField(
            model_name='liftmodels',
            name='LiftId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.LiftType', verbose_name='图片编号'),
        ),
    ]
