# Generated by Django 3.0.5 on 2020-05-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('ArticleID', models.CharField(default=0, max_length=128, verbose_name='文章类型')),
            ],
            options={
                'verbose_name': '文章类型',
                'verbose_name_plural': '文章类型',
                'db_table': 'df_ArticleType',
            },
        ),
        migrations.CreateModel(
            name='ArticleModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('ArticleName', models.CharField(max_length=128, verbose_name='文章名称')),
                ('ArticleBrief', models.CharField(max_length=256, verbose_name='文章简介')),
                ('ArticleDoc', models.FileField(null=True, upload_to='doc')),
                ('ArticleHtml', models.FileField(blank=True, null=True, upload_to='Html')),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.ArticleType', verbose_name='文章编号')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'df_Article',
            },
        ),
    ]
